### ISSUE TITLE
Specifying clusterIP as None prevents Service functionality

### ISSUE THREAD

**Issue by simon3z** [ManageIQ/manageiq-pods#141]
In the current template the `manageiq` service is specifying `clusterIP` as `None`. At least for me on OpenShift 3.5 this prevented the service from receiving a `clusterIP` remaining as `None`.

```yaml
...
- apiVersion: v1
  kind: Service
...
    name: ${NAME}
  spec:
    clusterIP: None
    ports:
...
```

The relevant `Route` seemed not to work.

Deleting and redefining the service without the `clusterIP` fixed the situation (a `clusterIP` was automatically assigned and the `Route` started working).

cc @fbladilo @bazulay
