### ISSUE TITLE
What image names/tags to use for 4.6?

### ISSUE THREAD

**Issue by tbielawa** [ManageIQ/manageiq-pods#227]
Hey folks,

In the 4.5 release we added this conditional logic to the openshift-ansible CFME role. It selected the correct image and tag name for installation based on if the user was doing an OSE or an Origin install:

```yaml
openshift_cfme_application_img_name: "{{ 'registry.access.redhat.com/cloudforms45/cfme-openshift-app' if openshift_deployment_type == 'openshift-enterprise' else 'docker.io/manageiq/manageiq-pods' }}"
openshift_cfme_application_img_tag: "{{ 'latest' if openshift_deployment_type == 'openshift-enterprise' else 'frontend-latest' }}"

openshift_cfme_memcached_img_name: "{{ 'registry.access.redhat.com/cloudforms45/cfme-openshift-memcached' if openshift_deployment_type == 'openshift-enterprise' else 'docker.io/manageiq/manageiq-pods' }}"
openshift_cfme_memcached_img_tag: "{{ 'latest' if openshift_deployment_type == 'openshift-enterprise' else 'memcached-latest-fine' }}"

openshift_cfme_postgresql_img_name: "{{ 'registry.access.redhat.com/cloudforms45/cfme-openshift-postgresql' if openshift_deployment_type == 'openshift-enterprise' else 'docker.io/manageiq/manageiq-pods' }}"
openshift_cfme_postgresql_img_tag: "{{ 'latest' if openshift_deployment_type == 'openshift-enterprise' else 'postgresql-latest-fine' }}"
```

Essentially it says

* Use `registry.access.redhat.com/cloudforms45/cfme-openshift-<IMAGE_NAME>` if installing openshift enterprise with `latest` tag
* Use `docker.io/manageiq/manageiq-pods` with a component specific image tag if installing origin (anything not openshift enterprise)

What are the new values for 4.6 going to be? Specifically, 

* Values like `frontend-latest` (image tags), will they be the same in 4.6?
* Will the image names be mostly similar, as in `registry.access.redhat.com/cloudforms45/....` just turns into `registry.access.redhat.com/cloudforms46/....` ?

Thanks!
