### ISSUE TITLE
Do not expose password in CR

### ISSUE THREAD

**Issue by gyliu513** [ManageIQ/manageiq-pods#499]
@miq-bot add_label bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

> According to Kubernetes official doc: https://kubernetes.io/docs/concepts/configuration/secret/
> 
> Kubernetes Secrets let you store and manage sensitive information, such as passwords, OAuth tokens, and ssh keys. Storing confidential information in a Secret is safer and more flexible than putting it verbatim in a Pod definition or in a container image.
> 
> Secret Design Doc: https://git.k8s.io/community/contributors/design-proposals/auth/secrets.md
> 
> According to: https://blog.aquasec.com/managing-kubernetes-secrets
> 
> Placing sensitive info into a secret object does not automatically make it secure. By default, data in Kubernetes secrets is stored in Base64 encoding, which is practically the same as plaintext.
> However, secrets give you more control over access and usage of passwords, keys, etc. Kubernetes can either mount secrets separately from the pods that use them, or save them as environment variables.

We are now putting password in CR as https://github.com/ManageIQ/manageiq-pods/blob/master/manageiq-operator/deploy/crds/manageiq.org_v1alpha1_manageiq_cr.yaml#L6 , this is not safe and it is better also use a secret as well.

FYI @carbonin @Fryguy @chessbyte

**Comment by carbonin** [comment]
This request would mean that a user will always need to pre-create a secret with a specific format and provide that secret name to us in the CR. Is that the user experience we want?

Is there some other solution that involves not using a default password as well as not providing the password in the CR?

**Comment by carbonin** [comment]
Specifically a yaml like this would be the minimum needed to deploy manageiq after this fix:

```yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: password-secret
  stringData:
    password: smartvm
- apiVersion: manageiq.org/v1alpha1
  kind: ManageIQ
  metadata:
    name: miq
  spec:
    adminPasswordSecret: password-secret
    applicationDomain: manageiq.apps-crc.testing
```

Should we make the CR example files this list as they won't work without defining the secret?
