### ISSUE TITLE
Image parameters for the images deployed by the operator should be consistent

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-pods#551]
While not a bug, per se, the inconsistency is a little strange.  Sometimes you specify the namespace separate, sometimes it's together, and sometimes it has docker.io as the default whereas other times it doesn't.  Not sure what the _right_ consistency would look like whether a single string we parse, or every possible piece as a separate value.

- [httpd](https://github.com/ManageIQ/manageiq-pods/blob/1e9c2d46f80a06d7cd2d609006249776eca2fae4/manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go#L288-L294)
- [memcached](https://github.com/ManageIQ/manageiq-pods/blob/1e9c2d46f80a06d7cd2d609006249776eca2fae4/manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go#L309-L315)
- [orchestrator itself](https://github.com/ManageIQ/manageiq-pods/blob/1e9c2d46f80a06d7cd2d609006249776eca2fae4/manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go#L329-L339)
- [postgres](https://github.com/ManageIQ/manageiq-pods/blob/1e9c2d46f80a06d7cd2d609006249776eca2fae4/manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go#L345-L351)
- [kafka](https://github.com/ManageIQ/manageiq-pods/blob/1e9c2d46f80a06d7cd2d609006249776eca2fae4/manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go#L345-L351)
- [zookeeper](https://github.com/ManageIQ/manageiq-pods/blob/1e9c2d46f80a06d7cd2d609006249776eca2fae4/manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go#L377-L383)

@miq-bot add-label enhancement

**Comment by jrafanie** [comment]
Along these lines, I had to push images and try to deploy them using my CR and it was trial and error to get it working and making these consistent would make this a lot easier.  

Additionally, extracting the default values out of the go code and into a template CR file that you can make a copy and edit would make the process of customizing the images you want to deploy much easier.

Here's the CR that I was able to get to work:

```
apiVersion: manageiq.org/v1alpha1
kind: ManageIQ
metadata:
  name: miq
spec:
  applicationDomain: gt-lj-manageiq-slow-fyre-httpd.x.x.x.x.xip.io
  baseWorkerImage: jrafanie/manageiq-base-worker:joe_latest7           # <--- namespace/repository:tag (no docker.io prefix)
  orchestratorImageNamespace: jrafanie                                 # <--- just the namespace
  orchestratorImageTag: joe_latest7                                    # <--- just the tag
  uiWorkerImage: jrafanie/manageiq-ui-worker:joe_latest7               # <--- namespace/repository:tag (no docker.io prefix)
  webserverWorkerImage: jrafanie/manageiq-webserver-worker:joe_latest7 # <--- namespace/repository:tag (no docker.io prefix)
 ```

cc @bdunne since we were chatting about this yesterday
